export const JWT_PUBLIC_KEY=process.env.JWT_PUBLIC_KEY ||
`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyiAZRp3OKaKnLzrEMiFW
6tRUCgS5X06rn5b4AujfvGkd5siLI2vPUp8F/e7oKiYrHXdMjLR7OA3OHRpQs/iw
RWQIWtd+MhQkqVrLCAFVFPP6Ez0Y6AL5sAKXipHqQBgpeZBAyUil1Of8MBrzgcHr
agj0reZj14VceEQBk9xfGY2rf7a2SoagOQruiZ8y9nRHUouyxRAIlHlx17lgwafd
Em4jQFUeSEqT+fGR1OTOvO/6fQo38VgEuHxZcqxLLUqOPkZDg+WnErIWxYnk5NRK
ymW2rJk2E0MFh3mDtWWMM0Pm8Xp8xOhuFcIZ71WuWJYGwbUmmI12/nGIChNzS7sI
dQIDAQAB
-----END PUBLIC KEY-----
`;